import type { Group } from "../types/entities";
import { hoursAgo, daysAgo } from "../utils";

export const groups: Group[] = [
  {
    id: "g1",
    name: "Les Potes",
    description: "Notre groupe de potes adores !",
    members: ["u1", "u2", "u3", "u4"],
    createdBy: "u1",
    messages: [
      { id: "gm1", senderId: "u2", content: "Coucou tout le monde !", type: "text", timestamp: daysAgo(3, 9) },
      { id: "gm2", senderId: "u3", content: "Salut les amis !", type: "text", timestamp: daysAgo(3, 10) },
      { id: "gm3", senderId: "u4", content: "Yo yo ! Bordeaux represent", type: "text", timestamp: daysAgo(3, 11) },
      { id: "gm4", senderId: "u1", content: "On se fait un trip ce weekend ?", type: "text", timestamp: daysAgo(2, 9) },
      { id: "gm5", senderId: "u2", content: "Bonne idee ! Lyon ou Paris ?", type: "text", timestamp: daysAgo(2, 10) },
      { id: "gm6", senderId: "u3", content: "Paris c'est loin de Marseille mais je suis partante !", type: "text", timestamp: daysAgo(2, 11) },
      { id: "gm7", senderId: "u4", content: "Je prends le train vendredi soir", type: "text", timestamp: daysAgo(1, 14) },
      { id: "gm8", senderId: "u1", content: "Super ! J'ai trouve un Airbnb pour 4", type: "text", timestamp: daysAgo(1, 15) },
      { id: "gm9", senderId: "u2", content: "Trop hate !!!", type: "text", timestamp: daysAgo(1, 16) },
      { id: "gm10", senderId: "u3", content: "Vous avez vu ma story des calanques ce matin ?", type: "text", timestamp: hoursAgo(6) },
      { id: "gm11", senderId: "u4", content: "Magnifique", type: "text", timestamp: hoursAgo(5) },
      { id: "gm12", senderId: "u1", content: "Je suis jalouse la", type: "text", timestamp: hoursAgo(4) },
      { id: "gm13", senderId: "u2", content: "On ira ensemble cet ete promis !", type: "text", timestamp: hoursAgo(2) },
    ],
    createdAt: daysAgo(14),
  },
  {
    id: "g2",
    name: "Projet Supinfo",
    description: "Groupe pour organiser notre projet scolaire",
    members: ["u1", "u2", "u6"],
    createdBy: "u1",
    messages: [
      { id: "gm20", senderId: "u1", content: "Bonjour a tous ! Voici notre groupe de projet", type: "text", timestamp: daysAgo(5, 9) },
      { id: "gm21", senderId: "u2", content: "Parfait, on peut commencer a s'organiser !", type: "text", timestamp: daysAgo(5, 10) },
      { id: "gm22", senderId: "u6", content: "Top ! Je m'occupe de la documentation", type: "text", timestamp: daysAgo(4, 14) },
      { id: "gm23", senderId: "u1", content: "Et moi je fais le frontend", type: "text", timestamp: daysAgo(4, 15) },
      { id: "gm24", senderId: "u2", content: "Je prends le backend alors", type: "text", timestamp: daysAgo(4, 16) },
      { id: "gm25", senderId: "u6", content: "On a une deadline pour quand ?", type: "text", timestamp: daysAgo(3, 11) },
      { id: "gm26", senderId: "u1", content: "La semaine prochaine... on a du boulot", type: "text", timestamp: daysAgo(3, 12) },
      { id: "gm27", senderId: "u2", content: "On peut se call demain soir pour faire le point ?", type: "text", timestamp: daysAgo(2, 18) },
      { id: "gm28", senderId: "u6", content: "Ok pour moi a 20h", type: "text", timestamp: daysAgo(2, 19) },
      { id: "gm29", senderId: "u1", content: "Pareil, a demain !", type: "text", timestamp: daysAgo(2, 20) },
      { id: "gm30", senderId: "u2", content: "La demo tourne bien de mon cote", type: "text", timestamp: hoursAgo(5) },
      { id: "gm31", senderId: "u1", content: "Nickel ! L'UI est presque finie", type: "text", timestamp: hoursAgo(3) },
    ],
    createdAt: daysAgo(21),
  },
  {
    id: "g3",
    name: "Voyageurs",
    description: "Pour partager nos aventures et planifier des trips !",
    members: ["u1", "u3", "u5", "u7", "u9"],
    createdBy: "u3",
    messages: [
      { id: "gm40", senderId: "u3", content: "Bienvenue dans ce groupe de voyageurs !", type: "text", timestamp: daysAgo(6, 10) },
      { id: "gm41", senderId: "u9", content: "Super idee Sophie !! Je suis trop contente d'etre la", type: "text", timestamp: daysAgo(6, 11) },
      { id: "gm42", senderId: "u5", content: "Trop hate de partager mes aventures avec vous !", type: "text", timestamp: daysAgo(6, 12) },
      { id: "gm43", senderId: "u7", content: "Pareil ! J'ai plein de spots sympas a Nantes a faire decouvrir", type: "text", timestamp: daysAgo(5, 14) },
      { id: "gm44", senderId: "u1", content: "Quelqu'un a des idees pour le prochain trip de groupe ?", type: "text", timestamp: daysAgo(4, 16) },
      { id: "gm45", senderId: "u9", content: "Nice en juillet ! La mer est incroyable", type: "text", timestamp: daysAgo(4, 17) },
      { id: "gm46", senderId: "u3", content: "Ou Marseille, on peut louer un bateau pour les calanques", type: "text", timestamp: daysAgo(3, 10) },
      { id: "gm47", senderId: "u5", content: "Je vote Marseille + Calanques !", type: "text", timestamp: daysAgo(3, 11) },
      { id: "gm48", senderId: "u7", content: "Idem !", type: "text", timestamp: daysAgo(3, 12) },
      { id: "gm49", senderId: "u1", content: "Vote Marseille aussi", type: "text", timestamp: daysAgo(2, 9) },
      { id: "gm50", senderId: "u9", content: "Ok Marseille c'est parti ! On vise quand ?", type: "text", timestamp: daysAgo(2, 10) },
      { id: "gm51", senderId: "u3", content: "Week-end du 12-14 juillet ?", type: "text", timestamp: daysAgo(1, 15) },
      { id: "gm52", senderId: "u5", content: "Parfait pour moi !", type: "text", timestamp: hoursAgo(8) },
      { id: "gm53", senderId: "u7", content: "Ok pour moi aussi", type: "text", timestamp: hoursAgo(5) },
      { id: "gm54", senderId: "u1", content: "Je commence a regarder les locations", type: "text", timestamp: hoursAgo(2) },
    ],
    createdAt: daysAgo(42),
  },
];
