import type { Story } from "../types/entities";
import { hoursAgo, hoursFromNow } from "../utils";

export const stories: Story[] = [
  {
    id: "s1",
    userId: "u1",
    imageUrl: "https://picsum.photos/seed/paris1/400/700",
    caption: "Tour Eiffel au coucher du soleil",
    location: { lat: 48.8566, lng: 2.3522, city: "Paris" },
    createdAt: hoursAgo(2),
    expiresAt: hoursFromNow(22),
  },
  {
    id: "s2",
    userId: "u1",
    imageUrl: "https://picsum.photos/seed/paris2/400/700",
    caption: "Balade sur les quais de Seine ce matin",
    location: { lat: 48.8566, lng: 2.3522, city: "Paris" },
    createdAt: hoursAgo(5),
    expiresAt: hoursFromNow(19),
  },
  {
    id: "s3",
    userId: "u2",
    imageUrl: "https://picsum.photos/seed/lyon1/400/700",
    caption: "La Fourviere sous le soleil, c'est trop beau",
    location: { lat: 45.764, lng: 4.8357, city: "Lyon" },
    createdAt: hoursAgo(8),
    expiresAt: hoursFromNow(16),
  },
  {
    id: "s4",
    userId: "u2",
    imageUrl: "https://picsum.photos/seed/lyon2/400/700",
    caption: "Bouchon lyonnais ce soir, c'est trop bon !",
    location: { lat: 45.764, lng: 4.8357, city: "Lyon" },
    createdAt: hoursAgo(3),
    expiresAt: hoursFromNow(21),
  },
  {
    id: "s5",
    userId: "u3",
    imageUrl: "https://picsum.photos/seed/marseille1/400/700",
    caption: "La mer est magnifique aujourd'hui #Calanques",
    location: { lat: 43.2965, lng: 5.3698, city: "Marseille" },
    createdAt: hoursAgo(12),
    expiresAt: hoursFromNow(12),
  },
  {
    id: "s6",
    userId: "u3",
    imageUrl: "https://picsum.photos/seed/marseille2/400/700",
    caption: "Sunset sur le Vieux-Port #Marseille #Beautiful",
    location: { lat: 43.2965, lng: 5.3698, city: "Marseille" },
    createdAt: hoursAgo(1),
    expiresAt: hoursFromNow(23),
  },
  {
    id: "s7",
    userId: "u4",
    imageUrl: "https://picsum.photos/seed/bordeaux1/400/700",
    caption: "Degustation au chateau ce matin #Gironde",
    location: { lat: 44.8378, lng: -0.5792, city: "Bordeaux" },
    createdAt: hoursAgo(6),
    expiresAt: hoursFromNow(18),
  },
  {
    id: "s8",
    userId: "u4",
    imageUrl: "https://picsum.photos/seed/bordeaux2/400/700",
    caption: "Place de la Bourse en soiree, magnifique",
    location: { lat: 44.8378, lng: -0.5792, city: "Bordeaux" },
    createdAt: hoursAgo(10),
    expiresAt: hoursFromNow(14),
  },
  {
    id: "s9",
    userId: "u5",
    imageUrl: "https://picsum.photos/seed/toulouse1/400/700",
    caption: "La ville rose sous le ciel bleu #Toulouse",
    location: { lat: 43.6047, lng: 1.4442, city: "Toulouse" },
    createdAt: hoursAgo(4),
    expiresAt: hoursFromNow(20),
  },
  {
    id: "s10",
    userId: "u5",
    imageUrl: "https://picsum.photos/seed/toulouse2/400/700",
    caption: "Expo a l'Abattoir, des artistes incroyables",
    location: { lat: 43.6047, lng: 1.4442, city: "Toulouse" },
    createdAt: hoursAgo(7),
    expiresAt: hoursFromNow(17),
  },
  {
    id: "s11",
    userId: "u6",
    imageUrl: "https://picsum.photos/seed/lille1/400/700",
    caption: "Grand Place de Lille en soiree #Lille",
    location: { lat: 50.6292, lng: 3.0573, city: "Lille" },
    createdAt: hoursAgo(9),
    expiresAt: hoursFromNow(15),
  },
  {
    id: "s12",
    userId: "u7",
    imageUrl: "https://picsum.photos/seed/nantes1/400/700",
    caption: "Les Machines de l'ile, c'est incroyable #Nantes",
    location: { lat: 47.2184, lng: -1.5536, city: "Nantes" },
    createdAt: hoursAgo(5),
    expiresAt: hoursFromNow(19),
  },
  {
    id: "s13",
    userId: "u7",
    imageUrl: "https://picsum.photos/seed/nantes2/400/700",
    caption: "Bords de l'Erdre ce matin",
    location: { lat: 47.2184, lng: -1.5536, city: "Nantes" },
    createdAt: hoursAgo(11),
    expiresAt: hoursFromNow(13),
  },
  {
    id: "s14",
    userId: "u8",
    imageUrl: "https://picsum.photos/seed/stras1/400/700",
    caption: "Vieille ville magnifique au crepuscule #Strasbourg",
    location: { lat: 48.5734, lng: 7.7521, city: "Strasbourg" },
    createdAt: hoursAgo(7),
    expiresAt: hoursFromNow(17),
  },
  {
    id: "s15",
    userId: "u9",
    imageUrl: "https://picsum.photos/seed/nice1/400/700",
    caption: "La Promenade des Anglais sous le soleil #Nice",
    location: { lat: 43.7102, lng: 7.262, city: "Nice" },
    createdAt: hoursAgo(3),
    expiresAt: hoursFromNow(21),
  },
  {
    id: "s16",
    userId: "u9",
    imageUrl: "https://picsum.photos/seed/nice2/400/700",
    caption: "Baignade dans une eau turquoise",
    location: { lat: 43.7102, lng: 7.262, city: "Nice" },
    createdAt: hoursAgo(6),
    expiresAt: hoursFromNow(18),
  },
  {
    id: "s17",
    userId: "u10",
    imageUrl: "https://picsum.photos/seed/montpellier1/400/700",
    caption: "Place de la Comedie ce soir #Montpellier",
    location: { lat: 43.6119, lng: 3.8772, city: "Montpellier" },
    createdAt: hoursAgo(4),
    expiresAt: hoursFromNow(20),
  },
  {
    id: "s18",
    userId: "u11",
    imageUrl: "https://picsum.photos/seed/rennes1/400/700",
    caption: "Vieux Rennes sous la pluie, mais tellement beau",
    location: { lat: 48.1173, lng: -1.6778, city: "Rennes" },
    createdAt: hoursAgo(8),
    expiresAt: hoursFromNow(16),
  },
  {
    id: "s19",
    userId: "u12",
    imageUrl: "https://picsum.photos/seed/grenoble1/400/700",
    caption: "Les Alpes depuis ma fenetre ce matin #Grenoble",
    location: { lat: 45.1885, lng: 5.7245, city: "Grenoble" },
    createdAt: hoursAgo(2),
    expiresAt: hoursFromNow(22),
  },
  {
    id: "s20",
    userId: "u12",
    imageUrl: "https://picsum.photos/seed/grenoble2/400/700",
    caption: "Premiere descente de la saison #Ski #Chamrousse",
    location: { lat: 45.1885, lng: 5.7245, city: "Grenoble" },
    createdAt: hoursAgo(13),
    expiresAt: hoursFromNow(11),
  },
];
