import type { User } from "../types/entities";
import { daysAgo } from "../utils";

export const users: User[] = [
  {
    id: "u1",
    email: "marie@beunreal.com",
    password: "password123",
    username: "Marie Dupont",
    bio: "Passionnee de photo | Parisienne",
    avatar: "https://i.pravatar.cc/150?img=1",
    location: { lat: 48.8566, lng: 2.3522, city: "Paris" },
    friends: ["u2", "u3", "u4", "u5"],
    createdAt: daysAgo(30),
  },
  {
    id: "u2",
    email: "thomas@beunreal.com",
    password: "password123",
    username: "Thomas Martin",
    bio: "Musicien | Lyon forever",
    avatar: "https://i.pravatar.cc/150?img=3",
    location: { lat: 45.764, lng: 4.8357, city: "Lyon" },
    friends: ["u1", "u3", "u4"],
    createdAt: daysAgo(25),
  },
  {
    id: "u3",
    email: "sophie@beunreal.com",
    password: "password123",
    username: "Sophie Bernard",
    bio: "La mer c'est la vie | Marseille",
    avatar: "https://i.pravatar.cc/150?img=5",
    location: { lat: 43.2965, lng: 5.3698, city: "Marseille" },
    friends: ["u1", "u2", "u5"],
    createdAt: daysAgo(20),
  },
  {
    id: "u4",
    email: "lucas@beunreal.com",
    password: "password123",
    username: "Lucas Petit",
    bio: "Amateur de bons vins | Bordeaux",
    avatar: "https://i.pravatar.cc/150?img=7",
    location: { lat: 44.8378, lng: -0.5792, city: "Bordeaux" },
    friends: ["u1", "u2"],
    createdAt: daysAgo(15),
  },
  {
    id: "u5",
    email: "emma@beunreal.com",
    password: "password123",
    username: "Emma Rousseau",
    bio: "Artiste & creative | Toulouse la rose",
    avatar: "https://i.pravatar.cc/150?img=9",
    location: { lat: 43.6047, lng: 1.4442, city: "Toulouse" },
    friends: ["u1", "u3"],
    createdAt: daysAgo(10),
  },
  {
    id: "u6",
    email: "hugo@beunreal.com",
    password: "password123",
    username: "Hugo Moreau",
    bio: "Fan de foot | Ch'ti fier",
    avatar: "https://i.pravatar.cc/150?img=12",
    location: { lat: 50.6292, lng: 3.0573, city: "Lille" },
    friends: ["u7"],
    createdAt: daysAgo(8),
  },
  {
    id: "u7",
    email: "camille@beunreal.com",
    password: "password123",
    username: "Camille Simon",
    bio: "Nature & Voyage | Nantes",
    avatar: "https://i.pravatar.cc/150?img=20",
    location: { lat: 47.2184, lng: -1.5536, city: "Nantes" },
    friends: ["u6"],
    createdAt: daysAgo(5),
  },
  {
    id: "u8",
    email: "antoine@beunreal.com",
    password: "password123",
    username: "Antoine Lefebvre",
    bio: "Histoire & Culture | Strasbourg",
    avatar: "https://i.pravatar.cc/150?img=33",
    location: { lat: 48.5734, lng: 7.7521, city: "Strasbourg" },
    friends: ["u9"],
    createdAt: daysAgo(3),
  },
  {
    id: "u9",
    email: "lea@beunreal.com",
    password: "password123",
    username: "Lea Fontaine",
    bio: "Soleil & plage | Nice",
    avatar: "https://i.pravatar.cc/150?img=16",
    location: { lat: 43.7102, lng: 7.262, city: "Nice" },
    friends: ["u8", "u10"],
    createdAt: daysAgo(12),
  },
  {
    id: "u10",
    email: "nathan@beunreal.com",
    password: "password123",
    username: "Nathan Girard",
    bio: "Developpeur | Montpellier",
    avatar: "https://i.pravatar.cc/150?img=25",
    location: { lat: 43.6119, lng: 3.8772, city: "Montpellier" },
    friends: ["u9"],
    createdAt: daysAgo(7),
  },
  {
    id: "u11",
    email: "chloe@beunreal.com",
    password: "password123",
    username: "Chloe Dubois",
    bio: "Etudiante en archi | Rennes",
    avatar: "https://i.pravatar.cc/150?img=44",
    location: { lat: 48.1173, lng: -1.6778, city: "Rennes" },
    friends: [],
    createdAt: daysAgo(4),
  },
  {
    id: "u12",
    email: "maxime@beunreal.com",
    password: "password123",
    username: "Maxime Leroy",
    bio: "Montagne & ski | Grenoble",
    avatar: "https://i.pravatar.cc/150?img=52",
    location: { lat: 45.1885, lng: 5.7245, city: "Grenoble" },
    friends: [],
    createdAt: daysAgo(2),
  },
];
